stages:
  - deploy

integration:
  stage: deploy
  script: 
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - rm -rf /home/ec2-user/py-api/rocketg-api-python-integration/*
  - mv ./* /home/ec2-user/py-api/rocketg-api-python-integration/
  - source /home/ec2-user/py-api/venv/bin/activate
  - pip3 install -r /home/ec2-user/py-api/rocketg-api-python-integration/requirements.txt
  - python3 /home/ec2-user/py-api/rocketg-api-python-integration/manage.py makemigrations
  - python3 /home/ec2-user/py-api/rocketg-api-python-integration/manage.py migrate --database integration
  - python3 /home/ec2-user/py-api/rocketg-api-python-integration/manage.py test
  
  only:
  - integration
  tags:
  - py-deploy-runner

staging:
  stage: deploy
  script: 
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip3 install -r requirements.txt
  - python3 manage.py migrate --database=staging
  - python3 manage.py test
  - rm -rf /home/ec2-user/py-api/rocketg-api-python-staging/*
  - mv ./* /home/ec2-user/py-api/rocketg-api-python-staging/
  only:
  - staging
  tags:
  - py-deploy-runner

production:
  stage: deploy
  script: 
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip3 install -r requirements.txt
  - python3 manage.py migrate --database=production
  - python3 manage.py test
  - rm -rf /home/ec2-user/py-api/rocketg-api-python/*
  - mv ./* /home/ec2-user/py-api/rocketg-api-python/
  only:
  - production
  tags:
  - py-deploy-runner

