stages:
  - deploy

staging:
  stage: deploy
  script: 
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip3 install -r requirements.txt
  - python3 manage.py test
  - rm -rf /home/ec2-user/py-api/rocketg-api-cdci-test
  - mv ./ /home/ec2-user/py-api/rocketg-api-cdci-test
  only:
  - master
  tags:
  - py-deploy-runner

#production:
#  stage: deploy
#  script:
#  - apt-get update -qy
#  - apt-get install -y ruby-dev
#  - gem install dpl
#  - heroku config:set DISABLE_COLLECTSTATIC=1
#  - dpl --provider=heroku --app=gitlab-py-cicd-test-prod --api-key=$HEROKU_PRODUCTION_API_KEY
#  only:
#  - master
