# Generated by Django 2.2.7 on 2020-01-07 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='report',
        ),
    ]
