# Generated by Django 2.2.7 on 2020-01-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20200107_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='currency_type',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
