# Generated by Django 2.2.7 on 2020-01-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20200109_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='reimbursement_cycle',
            field=models.IntegerField(default=0),
        ),
    ]
