# Generated by Django 2.2.7 on 2020-01-16 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_users_reimbursement_cycle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenseFile',
        ),
    ]
