# Generated by Django 2.2.7 on 2020-01-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_delete_expensefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='payments_currency',
            field=models.IntegerField(default=3),
        ),
    ]
