# Generated by Django 2.2.7 on 2020-01-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_reports_payments_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.IntegerField(default=0),
        ),
    ]
