# Generated by Django 2.2.7 on 2020-02-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_auto_20200117_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='special_privilege',
            field=models.IntegerField(default=0),
        ),
    ]
