# Generated by Django 2.2.7 on 2020-02-26 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_auto_20200216_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='approve_id',
            new_name='approve_user_id',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='processing_id',
            new_name='processing_user_id',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='reimburse_id',
            new_name='reimburse_user_id',
        ),
        migrations.AddField(
            model_name='expenses',
            name='approve_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_approve_user', to='apis.Users'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='open_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_open_user', to='apis.Users'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='processing_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_processing_user', to='apis.Users'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='reimburse_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_reimburse_user', to='apis.Users'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_user', to='apis.Users'),
        ),
    ]
