# Generated by Django 2.2.7 on 2020-02-26 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_auto_20200226_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='approve_user_id',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='open_user_id',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='processing_user_id',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='reimburse_user_id',
        ),
        migrations.AddField(
            model_name='companies',
            name='approve_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_approve_user', to='apis.Users'),
        ),
        migrations.AddField(
            model_name='companies',
            name='open_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_open_user', to='apis.Users'),
        ),
        migrations.AddField(
            model_name='companies',
            name='processing_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_processing_user', to='apis.Users'),
        ),
        migrations.AddField(
            model_name='companies',
            name='reimburse_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_reimburse_user', to='apis.Users'),
        ),
    ]
