# Generated by Django 2.2.7 on 2020-03-06 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_dsession'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dsession',
            new_name='Dsessions',
        ),
    ]
