# Generated by Django 2.2.7 on 2020-03-23 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_auto_20200306_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporter_user', to='apis.Users'),
        ),
    ]
