# Generated by Django 2.2.7 on 2020-04-05 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0020_companies_step_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='paylips_count_index',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Paylips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('file_urls', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Users')),
            ],
        ),
    ]
