# Generated by Django 2.2.7 on 2020-04-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0023_auto_20200405_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='currency_type',
            field=models.CharField(default='CNY', max_length=3),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='payments_currency',
            field=models.CharField(default='CNY', max_length=3),
        ),
        migrations.AlterField(
            model_name='reports',
            name='payments_currency',
            field=models.CharField(default='CNY', max_length=3),
        ),
        migrations.AlterField(
            model_name='users',
            name='payments_currency',
            field=models.CharField(default='CNY', max_length=3),
        ),
    ]
